{
    "connection": {
        "preferedResponseName": null
    },
    "request": {
        "_readableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "buffer": {
                "head": null,
                "tail": null,
                "length": 0
            },
            "length": 0,
            "pipes": null,
            "pipesCount": 0,
            "flowing": true,
            "ended": true,
            "endEmitted": true,
            "reading": false,
            "sync": false,
            "needReadable": false,
            "emittedReadable": false,
            "readableListening": false,
            "resumeScheduled": false,
            "destroyed": false,
            "defaultEncoding": "utf8",
            "awaitDrain": 0,
            "readingMore": false,
            "decoder": null,
            "encoding": null
        },
        "readable": false,
        "domain": null,
        "_events": {},
        "_eventsCount": 0,
        "httpVersionMajor": 1,
        "httpVersionMinor": 1,
        "httpVersion": "1.1",
        "complete": true,
        "headers": {
            "host": "ws-expose.mybluemix.net",
            "user-agent": "GitHub-Hookshot/3704bc9",
            "content-length": "7395",
            "$wscs": "ECDHE-RSA-AES256-GCM-SHA384",
            "$wsis": "true",
            "$wsra": "192.30.252.39",
            "$wssc": "https",
            "$wssn": "ws-expose.mybluemix.net",
            "$wssp": "443",
            "accept": "*/*",
            "content-type": "application/json",
            "via": "1.1 DQAAABWubhQ-",
            "x-b3-spanid": "04a46884a71b619f",
            "x-b3-traceid": "04a46884a71b619f",
            "x-cf-applicationid": "e68f5516-a561-42c7-ac49-af54fea27ed3",
            "x-cf-instanceid": "942a6057-2eaa-4911-7f26-b62a",
            "x-cf-instanceindex": "0",
            "x-client-ip": "192.30.252.39",
            "x-forwarded-for": "192.30.252.39, 10.84.125.26",
            "x-forwarded-proto": "https",
            "x-github-delivery": "73004cbe-95fc-11e8-9518-033b0598ed95",
            "x-github-event": "push",
            "x-global-transaction-id": "2073675959",
            "x-hub-signature": "sha1=65cbb10885d86f111b2e3ecf7255e81bb13e2d42",
            "x-request-start": "1533177213080",
            "x-vcap-request-id": "70ae4a70-0557-4d70-6d06-e323e99a7b64"
        },
        "rawHeaders": ["Host", "ws-expose.mybluemix.net", "User-Agent", "GitHub-Hookshot/3704bc9", "Content-Length", "7395", "$wscs", "ECDHE-RSA-AES256-GCM-SHA384", "$wsis", "true", "$wsra", "192.30.252.39", "$wssc", "https", "$wssn", "ws-expose.mybluemix.net", "$wssp", "443", "Accept", "*/*", "Content-Type", "application/json", "Via", "1.1 DQAAABWubhQ-", "X-B3-Spanid", "04a46884a71b619f", "X-B3-Traceid", "04a46884a71b619f", "X-Cf-Applicationid", "e68f5516-a561-42c7-ac49-af54fea27ed3", "X-Cf-Instanceid", "942a6057-2eaa-4911-7f26-b62a", "X-Cf-Instanceindex", "0", "X-Client-Ip", "192.30.252.39", "X-Forwarded-For", "192.30.252.39, 10.84.125.26", "X-Forwarded-Proto", "https", "X-Github-Delivery", "73004cbe-95fc-11e8-9518-033b0598ed95", "X-Github-Event", "push", "X-Global-Transaction-Id", "2073675959", "X-Hub-Signature", "sha1=65cbb10885d86f111b2e3ecf7255e81bb13e2d42", "X-Request-Start", "1533177213080", "X-Vcap-Request-Id", "70ae4a70-0557-4d70-6d06-e323e99a7b64"],
        "trailers": {},
        "rawTrailers": [],
        "upgrade": false,
        "url": "/?token=token3",
        "method": "POST",
        "statusCode": null,
        "statusMessage": null,
        "_consuming": true,
        "_dumped": false,
        "baseUrl": "/v1/github",
        "originalUrl": "/v1/github?token=token3",
        "_parsedUrl": {
            "protocol": null,
            "slashes": null,
            "auth": null,
            "host": null,
            "port": null,
            "hostname": null,
            "hash": null,
            "search": "?token=token3",
            "query": "token=token3",
            "pathname": "/v1/github",
            "path": "/v1/github?token=token3",
            "href": "/v1/github?token=token3",
            "_raw": "/v1/github?token=token3"
        },
        "params": {
            "0": "github"
        },
        "query": {
            "token": "token3"
        },
        "body": {
            "ref": "refs/heads/master",
            "before": "2241d07dc48070bb49be06341e34ee9e1ec75f54",
            "after": "d54e50f016949013e26cc539ff6d93f3cff4b197",
            "created": false,
            "deleted": false,
            "forced": false,
            "base_ref": null,
            "compare": "https://github.com/yeltnar/ws-expose-client/compare/2241d07dc480...d54e50f01694",
            "commits": [{
                "id": "d54e50f016949013e26cc539ff6d93f3cff4b197",
                "tree_id": "d34d16b6be8cc0ce4b15c0af8a9164622ba86cfa",
                "distinct": true,
                "message": "better default config values",
                "timestamp": "2018-08-01T21:33:25-05:00",
                "url": "https://github.com/yeltnar/ws-expose-client/commit/d54e50f016949013e26cc539ff6d93f3cff4b197",
                "author": {
                    "name": "Drew Brantley",
                    "email": "brantley@us.ibm.com",
                    "username": "acbrant"
                },
                "committer": {
                    "name": "Drew Brantley",
                    "email": "brantley@us.ibm.com",
                    "username": "acbrant"
                },
                "added": [],
                "removed": [],
                "modified": ["config/default.json"]
            }],
            "head_commit": {
                "id": "d54e50f016949013e26cc539ff6d93f3cff4b197",
                "tree_id": "d34d16b6be8cc0ce4b15c0af8a9164622ba86cfa",
                "distinct": true,
                "message": "better default config values",
                "timestamp": "2018-08-01T21:33:25-05:00",
                "url": "https://github.com/yeltnar/ws-expose-client/commit/d54e50f016949013e26cc539ff6d93f3cff4b197",
                "author": {
                    "name": "Drew Brantley",
                    "email": "brantley@us.ibm.com",
                    "username": "acbrant"
                },
                "committer": {
                    "name": "Drew Brantley",
                    "email": "brantley@us.ibm.com",
                    "username": "acbrant"
                },
                "added": [],
                "removed": [],
                "modified": ["config/default.json"]
            },
            "repository": {
                "id": 139187353,
                "node_id": "MDEwOlJlcG9zaXRvcnkxMzkxODczNTM=",
                "name": "ws-expose-client",
                "full_name": "yeltnar/ws-expose-client",
                "owner": {
                    "name": "yeltnar",
                    "email": "andcbrant@gmail.com",
                    "login": "yeltnar",
                    "id": 10929295,
                    "node_id": "MDQ6VXNlcjEwOTI5Mjk1",
                    "avatar_url": "https://avatars1.githubusercontent.com/u/10929295?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/yeltnar",
                    "html_url": "https://github.com/yeltnar",
                    "followers_url": "https://api.github.com/users/yeltnar/followers",
                    "following_url": "https://api.github.com/users/yeltnar/following{/other_user}",
                    "gists_url": "https://api.github.com/users/yeltnar/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/yeltnar/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/yeltnar/subscriptions",
                    "organizations_url": "https://api.github.com/users/yeltnar/orgs",
                    "repos_url": "https://api.github.com/users/yeltnar/repos",
                    "events_url": "https://api.github.com/users/yeltnar/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/yeltnar/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "private": false,
                "html_url": "https://github.com/yeltnar/ws-expose-client",
                "description": null,
                "fork": false,
                "url": "https://github.com/yeltnar/ws-expose-client",
                "forks_url": "https://api.github.com/repos/yeltnar/ws-expose-client/forks",
                "keys_url": "https://api.github.com/repos/yeltnar/ws-expose-client/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/yeltnar/ws-expose-client/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/yeltnar/ws-expose-client/teams",
                "hooks_url": "https://api.github.com/repos/yeltnar/ws-expose-client/hooks",
                "issue_events_url": "https://api.github.com/repos/yeltnar/ws-expose-client/issues/events{/number}",
                "events_url": "https://api.github.com/repos/yeltnar/ws-expose-client/events",
                "assignees_url": "https://api.github.com/repos/yeltnar/ws-expose-client/assignees{/user}",
                "branches_url": "https://api.github.com/repos/yeltnar/ws-expose-client/branches{/branch}",
                "tags_url": "https://api.github.com/repos/yeltnar/ws-expose-client/tags",
                "blobs_url": "https://api.github.com/repos/yeltnar/ws-expose-client/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/yeltnar/ws-expose-client/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/yeltnar/ws-expose-client/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/yeltnar/ws-expose-client/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/yeltnar/ws-expose-client/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/yeltnar/ws-expose-client/languages",
                "stargazers_url": "https://api.github.com/repos/yeltnar/ws-expose-client/stargazers",
                "contributors_url": "https://api.github.com/repos/yeltnar/ws-expose-client/contributors",
                "subscribers_url": "https://api.github.com/repos/yeltnar/ws-expose-client/subscribers",
                "subscription_url": "https://api.github.com/repos/yeltnar/ws-expose-client/subscription",
                "commits_url": "https://api.github.com/repos/yeltnar/ws-expose-client/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/yeltnar/ws-expose-client/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/yeltnar/ws-expose-client/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/yeltnar/ws-expose-client/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/yeltnar/ws-expose-client/contents/{+path}",
                "compare_url": "https://api.github.com/repos/yeltnar/ws-expose-client/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/yeltnar/ws-expose-client/merges",
                "archive_url": "https://api.github.com/repos/yeltnar/ws-expose-client/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/yeltnar/ws-expose-client/downloads",
                "issues_url": "https://api.github.com/repos/yeltnar/ws-expose-client/issues{/number}",
                "pulls_url": "https://api.github.com/repos/yeltnar/ws-expose-client/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/yeltnar/ws-expose-client/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/yeltnar/ws-expose-client/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/yeltnar/ws-expose-client/labels{/name}",
                "releases_url": "https://api.github.com/repos/yeltnar/ws-expose-client/releases{/id}",
                "deployments_url": "https://api.github.com/repos/yeltnar/ws-expose-client/deployments",
                "created_at": 1530300193,
                "updated_at": "2018-08-02T02:21:55Z",
                "pushed_at": 1533177212,
                "git_url": "git://github.com/yeltnar/ws-expose-client.git",
                "ssh_url": "git@github.com:yeltnar/ws-expose-client.git",
                "clone_url": "https://github.com/yeltnar/ws-expose-client.git",
                "svn_url": "https://github.com/yeltnar/ws-expose-client",
                "homepage": null,
                "size": 35,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "TypeScript",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": true,
                "has_pages": false,
                "forks_count": 0,
                "mirror_url": null,
                "archived": false,
                "open_issues_count": 0,
                "license": null,
                "forks": 0,
                "open_issues": 0,
                "watchers": 0,
                "default_branch": "master",
                "stargazers": 0,
                "master_branch": "master"
            },
            "pusher": {
                "name": "yeltnar",
                "email": "andcbrant@gmail.com"
            },
            "sender": {
                "login": "yeltnar",
                "id": 10929295,
                "node_id": "MDQ6VXNlcjEwOTI5Mjk1",
                "avatar_url": "https://avatars1.githubusercontent.com/u/10929295?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/yeltnar",
                "html_url": "https://github.com/yeltnar",
                "followers_url": "https://api.github.com/users/yeltnar/followers",
                "following_url": "https://api.github.com/users/yeltnar/following{/other_user}",
                "gists_url": "https://api.github.com/users/yeltnar/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/yeltnar/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/yeltnar/subscriptions",
                "organizations_url": "https://api.github.com/users/yeltnar/orgs",
                "repos_url": "https://api.github.com/users/yeltnar/repos",
                "events_url": "https://api.github.com/users/yeltnar/events{/privacy}",
                "received_events_url": "https://api.github.com/users/yeltnar/received_events",
                "type": "User",
                "site_admin": false
            }
        }
    },
    "errors": {},
    "date": "2018-08-02T02:33:33.084Z",
    "send_to_device": {
        "uuid": "ae64dc65-9740-408b-bf21-f90b199da84f",
        "index": 0
    }
}